// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		17.09.2015 10:21:02
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.Ifc2x3.ElectricalDomain
{
	public enum IfcLampTypeEnum
	{
		@COMPACTFLUORESCENT ,
		@FLUORESCENT ,
		@HIGHPRESSUREMERCURY ,
		@HIGHPRESSURESODIUM ,
		@METALHALIDE ,
		@TUNGSTENFILAMENT ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}