// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		16.09.2015 10:12:23
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace Xbim.Common
{
	[AttributeUsage(AttributeTargets.Class, Inherited = false)]
    public sealed class EntityNameAttribute : Attribute
    {
        public EntityNameAttribute(string name, int id)
        {
            Name = name;
			EntityTypeId = id;
        }

        public string Name { get; private set; }
        public int EntityTypeId { get; private set; }
    }

	[AttributeUsage(AttributeTargets.Property)]
    public sealed class EntityAttributeAttribute : Attribute
    {
        public int Index { get; private set; }
        public EntityAttributeState State { get; private set; }

        public EntityAttributeAttribute(int index, EntityAttributeState state)
        {
            Index = index;
            State = state;
        }

    }

    public enum EntityAttributeState
    {
        Optional,
        Mandatory
    }
}