// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		23.09.2015 10:21:54
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Xbim.Common
{
	public interface IExpressValueType : IPersist
    {
        Type UnderlyingSystemType { get; }
        object Value { get; }
    }

	public interface IExpressSelectType : IPersist
    {
    }

	public interface IExpressHeaderType
    {
    }

	public interface IExpressEnumerable : IEnumerable
    {
    }

	public interface IExpressValueComplexType : IExpressValueType
    {
        IEnumerable<object> Properties { get; }
        void Add(object o);
    }
}