// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		08/09/2015 02:29:26
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace Xbim.Common
{
	public interface ITransaction: IDisposable
	{
		void Commit();
		void RollBack();
		void AddReversibleAction(Action action);
	}
}