// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		22.09.2015 04:44:16
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.Ifc4.StructuralAnalysisDomain
{
	public enum IfcActionSourceTypeEnum
	{
		@DEAD_LOAD_G ,
		@COMPLETION_G1 ,
		@LIVE_LOAD_Q ,
		@SNOW_S ,
		@WIND_W ,
		@PRESTRESSING_P ,
		@SETTLEMENT_U ,
		@TEMPERATURE_T ,
		@EARTHQUAKE_E ,
		@FIRE ,
		@IMPULSE ,
		@IMPACT ,
		@TRANSPORT ,
		@ERECTION ,
		@PROPPING ,
		@SYSTEM_IMPERFECTION ,
		@SHRINKAGE ,
		@CREEP ,
		@LACK_OF_FIT ,
		@BUOYANCY ,
		@ICE ,
		@CURRENT ,
		@WAVE ,
		@RAIN ,
		@BRAKES ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}