// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		17.09.2015 10:21:12
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.Ifc4.StructuralAnalysisDomain
{
	public enum IfcAnalysisModelTypeEnum
	{
		@IN_PLANE_LOADING_2D ,
		@OUT_PLANE_LOADING_2D ,
		@LOADING_3D ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}