// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		23.09.2015 10:21:53
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.Ifc4.ProductExtension
{
	public enum IfcExternalSpatialElementTypeEnum
	{
		@EXTERNAL ,
		@EXTERNAL_EARTH ,
		@EXTERNAL_WATER ,
		@EXTERNAL_FIRE ,
		@USERDEFINED ,
		@NOTDEFIEND 
	}
}