// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		22.09.2015 04:44:07
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.Ifc2x3.MeasureResource
{
	public enum IfcSIPrefix
	{
		@EXA ,
		@PETA ,
		@TERA ,
		@GIGA ,
		@MEGA ,
		@KILO ,
		@HECTO ,
		@DECA ,
		@DECI ,
		@CENTI ,
		@MILLI ,
		@MICRO ,
		@NANO ,
		@PICO ,
		@FEMTO ,
		@ATTO 
	}
}