// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc2x3.Kernel;
using System.Collections.Generic;
using Xbim.Common;
using Xbim.Common.Exceptions;

namespace Xbim.Ifc2x3.ProductExtension
{
	[ExpressType("IFCPORT", 179)]
	// ReSharper disable once PartialTypeWithSinglePart
	public abstract partial class @IfcPort : IfcProduct, System.Collections.Generic.IEqualityComparer<@IfcPort>, System.IEquatable<@IfcPort>
	{
		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcPort(IModel model) : base(model) 		{ 
			Model = model; 
		}


		#region Inverse attributes
		[EntityAttribute(-1, EntityAttributeState.Mandatory, EntityAttributeType.Set, EntityAttributeType.Class, -1, -1)]
		public IfcRelConnectsPortToElement @ContainedIn 
		{ 
			get 
			{
				return Model.Instances.FirstOrDefault<IfcRelConnectsPortToElement>(e => e.RelatingPort == this);
			} 
		}
		[EntityAttribute(-1, EntityAttributeState.Mandatory, EntityAttributeType.Set, EntityAttributeType.Class, -1, -1)]
		public IEnumerable<IfcRelConnectsPorts> @ConnectedFrom 
		{ 
			get 
			{
				return Model.Instances.Where<IfcRelConnectsPorts>(e => e.RelatedPort == this);
			} 
		}
		[EntityAttribute(-1, EntityAttributeState.Mandatory, EntityAttributeType.Set, EntityAttributeType.Class, -1, -1)]
		public IEnumerable<IfcRelConnectsPorts> @ConnectedTo 
		{ 
			get 
			{
				return Model.Instances.Where<IfcRelConnectsPorts>(e => e.RelatingPort == this);
			} 
		}
		#endregion


		#region IPersist implementation
		public  override void Parse(int propIndex, IPropertyValue value)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
				case 2: 
				case 3: 
				case 4: 
				case 5: 
				case 6: 
					base.Parse(propIndex, value); 
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		
		public  override string WhereRule() 
		{
			return "";
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@IfcPort other)
	    {
	        return this == other;
	    }


        public static bool operator ==(@IfcPort left, @IfcPort right)
        {
            // If both are null, or both are same instance, return true.
            if (ReferenceEquals(left, right))
                return true;

            // If one is null, but not both, return false.
            if (ReferenceEquals(left, null) || ReferenceEquals(right, null))
                return false;

            return (left.EntityLabel == right.EntityLabel) && (left.Model == right.Model);

        }

        public static bool operator !=(@IfcPort left, @IfcPort right)
        {
            return !(left == right);
        }


        public bool Equals(@IfcPort x, @IfcPort y)
        {
            return x == y;
        }

        public int GetHashCode(@IfcPort obj)
        {
            return obj == null ? -1 : obj.GetHashCode();
        }
        #endregion
	}
}