// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		08/09/2015 09:16:42
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Kernel;
using Xbim.Ifc4.UtilityResource;
using Xbim.Ifc4.MeasureResource;
using Xbim.Ifc4.DateTimeResource;
using System.Collections.Generic;
using Xbim.Common;

namespace Xbim.Ifc4.ProcessExtension
{
	[EntityName("IFCEVENT")]
	public  partial class @IfcEvent : IfcProcess, IInstantiableEntity
	{
		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcEvent(IModel model) : base(model) 		{ 
			Model = model; 
		}

		#region Explicit attribute fields
		private IfcEventTypeEnum _predefinedType;
		private IfcEventTriggerTypeEnum _eventTriggerType;
		private IfcLabel? _userDefinedEventTriggerType;
		private IfcEventTime _eventOccurenceTime;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(7, EntityAttributeState.Optional)]
		public IfcEventTypeEnum @PredefinedType 
		{ 
			get 
			{
				if(IsActivated) return _predefinedType;
				
				Model.Activate(this, true);
				IsActivated = true;
				return _predefinedType;
			} 
			set
			{
				SetValue( v =>  _predefinedType = v, _predefinedType, value,  "PredefinedType");
			} 
		}
	
		[EntityAttribute(8, EntityAttributeState.Optional)]
		public IfcEventTriggerTypeEnum @EventTriggerType 
		{ 
			get 
			{
				if(IsActivated) return _eventTriggerType;
				
				Model.Activate(this, true);
				IsActivated = true;
				return _eventTriggerType;
			} 
			set
			{
				SetValue( v =>  _eventTriggerType = v, _eventTriggerType, value,  "EventTriggerType");
			} 
		}
	
		[EntityAttribute(9, EntityAttributeState.Optional)]
		public IfcLabel? @UserDefinedEventTriggerType 
		{ 
			get 
			{
				if(IsActivated) return _userDefinedEventTriggerType;
				
				Model.Activate(this, true);
				IsActivated = true;
				return _userDefinedEventTriggerType;
			} 
			set
			{
				SetValue( v =>  _userDefinedEventTriggerType = v, _userDefinedEventTriggerType, value,  "UserDefinedEventTriggerType");
			} 
		}
	
		[EntityAttribute(10, EntityAttributeState.Optional)]
		public IfcEventTime @EventOccurenceTime 
		{ 
			get 
			{
				if(IsActivated) return _eventOccurenceTime;
				
				Model.Activate(this, true);
				IsActivated = true;
				return _eventOccurenceTime;
			} 
			set
			{
				SetValue( v =>  _eventOccurenceTime = v, _eventOccurenceTime, value,  "EventOccurenceTime");
			} 
		}
	
		#endregion

		#region Inverse attributes

		#endregion

		#region Index access
		private readonly List<string> _attributeNames = new List<string>
		{
			"GlobalId",
			"OwnerHistory",
			"Name",
			"Description",
			"ObjectType",
			"Identification",
			"LongDescription",
			"PredefinedType",
			"EventTriggerType",
			"UserDefinedEventTriggerType",
			"EventOccurenceTime",
		};

		IEnumerable<string> IInstantiableEntity.PropertyNames { get { return _attributeNames; } }

		object IInstantiableEntity.GetValue(int index)
		{
			switch(index)
			{
				case 0: 
					return @GlobalId;
				case 1: 
					return @OwnerHistory;
				case 2: 
					return @Name;
				case 3: 
					return @Description;
				case 4: 
					return @ObjectType;
				case 5: 
					return @Identification;
				case 6: 
					return @LongDescription;
				case 7: 
					return @PredefinedType;
				case 8: 
					return @EventTriggerType;
				case 9: 
					return @UserDefinedEventTriggerType;
				case 10: 
					return @EventOccurenceTime;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		object IInstantiableEntity.GetValue(string name)
		{
			switch(name)
			{
				case "GlobalId":  
					return @GlobalId;
				case "OwnerHistory":  
					return @OwnerHistory;
				case "Name":  
					return @Name;
				case "Description":  
					return @Description;
				case "ObjectType":  
					return @ObjectType;
				case "Identification":  
					return @Identification;
				case "LongDescription":  
					return @LongDescription;
				case "PredefinedType":  
					return @PredefinedType;
				case "EventTriggerType":  
					return @EventTriggerType;
				case "UserDefinedEventTriggerType":  
					return @UserDefinedEventTriggerType;
				case "EventOccurenceTime":  
					return @EventOccurenceTime;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(int index, object value)
		{
			switch(index)
			{
				case 0:
					 if (value != null) @GlobalId = (IfcGloballyUniqueId)value;
					 break;
				case 1:
					 @OwnerHistory = (IfcOwnerHistory)value;
					 break;
				case 2:
					 @Name = (IfcLabel?)value;
					 break;
				case 3:
					 @Description = (IfcText?)value;
					 break;
				case 4:
					 @ObjectType = (IfcLabel?)value;
					 break;
				case 5:
					 @Identification = (IfcIdentifier?)value;
					 break;
				case 6:
					 @LongDescription = (IfcText?)value;
					 break;
				case 7:
					 @PredefinedType = (IfcEventTypeEnum)value;
					 break;
				case 8:
					 @EventTriggerType = (IfcEventTriggerTypeEnum)value;
					 break;
				case 9:
					 @UserDefinedEventTriggerType = (IfcLabel?)value;
					 break;
				case 10:
					 @EventOccurenceTime = (IfcEventTime)value;
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(string propName, object value)
		{
			switch(propName)
			{
				case "GlobalId":
					 if (value != null) @GlobalId = (IfcGloballyUniqueId)value;
					 break;
				case "OwnerHistory":
					 @OwnerHistory = (IfcOwnerHistory)value;
					 break;
				case "Name":
					 @Name = (IfcLabel?)value;
					 break;
				case "Description":
					 @Description = (IfcText?)value;
					 break;
				case "ObjectType":
					 @ObjectType = (IfcLabel?)value;
					 break;
				case "Identification":
					 @Identification = (IfcIdentifier?)value;
					 break;
				case "LongDescription":
					 @LongDescription = (IfcText?)value;
					 break;
				case "PredefinedType":
					 @PredefinedType = (IfcEventTypeEnum)value;
					 break;
				case "EventTriggerType":
					 @EventTriggerType = (IfcEventTriggerTypeEnum)value;
					 break;
				case "UserDefinedEventTriggerType":
					 @UserDefinedEventTriggerType = (IfcLabel?)value;
					 break;
				case "EventOccurenceTime":
					 @EventOccurenceTime = (IfcEventTime)value;
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}
		#endregion

		#region Where rules
		/*CorrectPredefinedType:	CorrectPredefinedType : NOT(EXISTS(PredefinedType)) OR (PredefinedType <> IfcEventTypeEnum.USERDEFINED) OR ((PredefinedType = IfcEventTypeEnum.USERDEFINED) AND EXISTS(SELF\IfcObject.ObjectType));*/
		/*CorrectTypeAssigned:	CorrectTypeAssigned : NOT(EXISTS(EventTriggerType)) OR (EventTriggerType <> IfcEventTriggerTypeEnum.USERDEFINED) OR ((EventTriggerType = IfcEventTriggerTypeEnum.USERDEFINED) AND EXISTS(UserDefinedEventTriggerType));*/
		#endregion

		#region IPersist implementation
		public void Set(int propIndex, IPropertyValue value)
		{
            throw new System.NotImplementedException();
		}
		#endregion

	}
}