// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		08/09/2015 02:29:24
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Kernel;
using Xbim.Ifc4.UtilityResource;
using Xbim.Ifc4.MeasureResource;
using Xbim.Ifc4.DateTimeResource;
using System.Collections.Generic;
using Xbim.Common;

namespace Xbim.Ifc4.ProcessExtension
{
	[EntityName("IFCWORKCALENDAR", 759)]
	public  partial class @IfcWorkCalendar : IfcControl, IInstantiableEntity
	{
		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcWorkCalendar(IModel model) : base(model) 		{ 
			Model = model; 
			_workingTimes = new ItemSet<IfcWorkTime>( model );
			_exceptionTimes = new ItemSet<IfcWorkTime>( model );
		}

		#region Explicit attribute fields
		private ItemSet<IfcWorkTime> _workingTimes;
		private ItemSet<IfcWorkTime> _exceptionTimes;
		private IfcWorkCalendarTypeEnum _predefinedType;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(6, EntityAttributeState.Optional)]
		public ItemSet<IfcWorkTime> @WorkingTimes 
		{ 
			get 
			{
				if(Activated) return _workingTimes;
				
				Model.Activate(this, true);
				Activated = true;
				return _workingTimes;
			} 
			set
			{
				SetValue( v =>  _workingTimes = v, _workingTimes, value,  "WorkingTimes");
			} 
		}
	
		[EntityAttribute(7, EntityAttributeState.Optional)]
		public ItemSet<IfcWorkTime> @ExceptionTimes 
		{ 
			get 
			{
				if(Activated) return _exceptionTimes;
				
				Model.Activate(this, true);
				Activated = true;
				return _exceptionTimes;
			} 
			set
			{
				SetValue( v =>  _exceptionTimes = v, _exceptionTimes, value,  "ExceptionTimes");
			} 
		}
	
		[EntityAttribute(8, EntityAttributeState.Optional)]
		public IfcWorkCalendarTypeEnum @PredefinedType 
		{ 
			get 
			{
				if(Activated) return _predefinedType;
				
				Model.Activate(this, true);
				Activated = true;
				return _predefinedType;
			} 
			set
			{
				SetValue( v =>  _predefinedType = v, _predefinedType, value,  "PredefinedType");
			} 
		}
	
		#endregion

		#region Inverse attributes

		#endregion

		#region Index access
		private readonly List<string> _attributeNames = new List<string>
		{
			"GlobalId",
			"OwnerHistory",
			"Name",
			"Description",
			"ObjectType",
			"Identification",
			"WorkingTimes",
			"ExceptionTimes",
			"PredefinedType",
		};

		IEnumerable<string> IInstantiableEntity.PropertyNames { get { return _attributeNames; } }

		object IInstantiableEntity.GetValue(int index)
		{
			switch(index)
			{
				case 0: 
					return @GlobalId;
				case 1: 
					return @OwnerHistory;
				case 2: 
					return @Name;
				case 3: 
					return @Description;
				case 4: 
					return @ObjectType;
				case 5: 
					return @Identification;
				case 6: 
					return @WorkingTimes;
				case 7: 
					return @ExceptionTimes;
				case 8: 
					return @PredefinedType;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		object IInstantiableEntity.GetValue(string name)
		{
			switch(name)
			{
				case "GlobalId":  
					return @GlobalId;
				case "OwnerHistory":  
					return @OwnerHistory;
				case "Name":  
					return @Name;
				case "Description":  
					return @Description;
				case "ObjectType":  
					return @ObjectType;
				case "Identification":  
					return @Identification;
				case "WorkingTimes":  
					return @WorkingTimes;
				case "ExceptionTimes":  
					return @ExceptionTimes;
				case "PredefinedType":  
					return @PredefinedType;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(int index, object value)
		{
			switch(index)
			{
				case 0:
					 if (value != null) @GlobalId = (IfcGloballyUniqueId)value;
					 break;
				case 1:
					 @OwnerHistory = (IfcOwnerHistory)value;
					 break;
				case 2:
					 @Name = (IfcLabel?)value;
					 break;
				case 3:
					 @Description = (IfcText?)value;
					 break;
				case 4:
					 @ObjectType = (IfcLabel?)value;
					 break;
				case 5:
					 @Identification = (IfcIdentifier?)value;
					 break;
				case 6:
					 @WorkingTimes.Add((IfcWorkTime)value);
					 break;
				case 7:
					 @ExceptionTimes.Add((IfcWorkTime)value);
					 break;
				case 8:
					 @PredefinedType = (IfcWorkCalendarTypeEnum)value;
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(string propName, object value)
		{
			switch(propName)
			{
				case "GlobalId":
					 if (value != null) @GlobalId = (IfcGloballyUniqueId)value;
					 break;
				case "OwnerHistory":
					 @OwnerHistory = (IfcOwnerHistory)value;
					 break;
				case "Name":
					 @Name = (IfcLabel?)value;
					 break;
				case "Description":
					 @Description = (IfcText?)value;
					 break;
				case "ObjectType":
					 @ObjectType = (IfcLabel?)value;
					 break;
				case "Identification":
					 @Identification = (IfcIdentifier?)value;
					 break;
				case "WorkingTimes":
					 @WorkingTimes.Add((IfcWorkTime)value);
					 break;
				case "ExceptionTimes":
					 @ExceptionTimes.Add((IfcWorkTime)value);
					 break;
				case "PredefinedType":
					 @PredefinedType = (IfcWorkCalendarTypeEnum)value;
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}
		#endregion

		#region Where rules
		/*CorrectPredefinedType:                              ((PredefinedType = IfcWorkCalendarTypeEnum.USERDEFINED) AND EXISTS(SELF\IfcObject.ObjectType));*/
		#endregion

		#region IPersist implementation
		void IPersist.Set(int propIndex, IPropertyValue value)
		{
            throw new System.NotImplementedException();
		}
		#endregion

	}
}