// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		15.09.2015 07:04:19
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc2x3.MeasureResource;
using System.Collections.Generic;
using System.ComponentModel;
using System;
using Xbim.Common;

namespace Xbim.Ifc2x3.PresentationAppearanceResource
{
	[EntityName("IFCTEXTSTYLEWITHBOXCHARACTERISTICS", 730)]
	public  partial class @IfcTextStyleWithBoxCharacteristics : INotifyPropertyChanged, IfcTextStyleSelect, IInstantiableEntity
	{
		#region Implementation of IPersistEntity
		public int EntityLabel {get; internal set;}
		
		public IModel Model { get; internal set; }
		
		public bool Activated { get; internal set; }

		public void Activate(bool write)
		{
			if (Activated) return; //activation can only happen once in a lifetime of the object

			Model.Activate(this, write);
			Activated = true;
		}

		public void Activate (Action activation)
		{
			activation();
			Activated = true;
		}
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcTextStyleWithBoxCharacteristics(IModel model) 		{ 
			Model = model; 
		}

		#region Explicit attribute fields
		private IfcPositiveLengthMeasure? _boxHeight;
		private IfcPositiveLengthMeasure? _boxWidth;
		private IfcPlaneAngleMeasure? _boxSlantAngle;
		private IfcPlaneAngleMeasure? _boxRotateAngle;
		private IfcSizeSelect _characterSpacing;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(0, EntityAttributeState.Optional)]
		public IfcPositiveLengthMeasure? @BoxHeight 
		{ 
			get 
			{
				if(Activated) return _boxHeight;
				
				Model.Activate(this, true);
				Activated = true;
				return _boxHeight;
			} 
			set
			{
				SetValue( v =>  _boxHeight = v, _boxHeight, value,  "BoxHeight");
			} 
		}
	
		[EntityAttribute(1, EntityAttributeState.Optional)]
		public IfcPositiveLengthMeasure? @BoxWidth 
		{ 
			get 
			{
				if(Activated) return _boxWidth;
				
				Model.Activate(this, true);
				Activated = true;
				return _boxWidth;
			} 
			set
			{
				SetValue( v =>  _boxWidth = v, _boxWidth, value,  "BoxWidth");
			} 
		}
	
		[EntityAttribute(2, EntityAttributeState.Optional)]
		public IfcPlaneAngleMeasure? @BoxSlantAngle 
		{ 
			get 
			{
				if(Activated) return _boxSlantAngle;
				
				Model.Activate(this, true);
				Activated = true;
				return _boxSlantAngle;
			} 
			set
			{
				SetValue( v =>  _boxSlantAngle = v, _boxSlantAngle, value,  "BoxSlantAngle");
			} 
		}
	
		[EntityAttribute(3, EntityAttributeState.Optional)]
		public IfcPlaneAngleMeasure? @BoxRotateAngle 
		{ 
			get 
			{
				if(Activated) return _boxRotateAngle;
				
				Model.Activate(this, true);
				Activated = true;
				return _boxRotateAngle;
			} 
			set
			{
				SetValue( v =>  _boxRotateAngle = v, _boxRotateAngle, value,  "BoxRotateAngle");
			} 
		}
	
		[EntityAttribute(4, EntityAttributeState.Optional)]
		public IfcSizeSelect @CharacterSpacing 
		{ 
			get 
			{
				if(Activated) return _characterSpacing;
				
				Model.Activate(this, true);
				Activated = true;
				return _characterSpacing;
			} 
			set
			{
				SetValue( v =>  _characterSpacing = v, _characterSpacing, value,  "CharacterSpacing");
			} 
		}
	
		#endregion

		#region Inverse attributes

		#endregion

		#region INotifyPropertyChanged implementation
		 
		public event PropertyChangedEventHandler PropertyChanged;

		protected void NotifyPropertyChanged( string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

		#endregion

		#region Transactional property setting

		protected void SetValue<TProperty>(Action<TProperty> setter, TProperty oldValue, TProperty newValue, string notifyPropertyName)
		{

			if (!Model.IsTransactional)
			{
				setter(newValue);
				NotifyPropertyChanged(notifyPropertyName);
				return;
			}

			//check there is a transaction
			var txn = Model.CurrentTransaction;
			if (txn == null) throw new Exception("Operation out of transaction.");

			Action undo = () => setter(oldValue);
			txn.AddReversibleAction(undo);
			setter(newValue);
			NotifyPropertyChanged(notifyPropertyName);
		}

		#endregion

		#region Index access
		private readonly List<string> _attributeNames = new List<string>
		{
			"BoxHeight",
			"BoxWidth",
			"BoxSlantAngle",
			"BoxRotateAngle",
			"CharacterSpacing",
		};

		IEnumerable<string> IInstantiableEntity.PropertyNames { get { return _attributeNames; } }

		object IInstantiableEntity.GetValue(int index)
		{
			switch(index)
			{
				case 0: 
					return @BoxHeight;
				case 1: 
					return @BoxWidth;
				case 2: 
					return @BoxSlantAngle;
				case 3: 
					return @BoxRotateAngle;
				case 4: 
					return @CharacterSpacing;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		object IInstantiableEntity.GetValue(string name)
		{
			switch(name)
			{
				case "BoxHeight":  
					return @BoxHeight;
				case "BoxWidth":  
					return @BoxWidth;
				case "BoxSlantAngle":  
					return @BoxSlantAngle;
				case "BoxRotateAngle":  
					return @BoxRotateAngle;
				case "CharacterSpacing":  
					return @CharacterSpacing;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(int index, object value)
		{
			switch(index)
			{
				case 0:
					 @BoxHeight = (IfcPositiveLengthMeasure?)value;
					 break;
				case 1:
					 @BoxWidth = (IfcPositiveLengthMeasure?)value;
					 break;
				case 2:
					 @BoxSlantAngle = (IfcPlaneAngleMeasure?)value;
					 break;
				case 3:
					 @BoxRotateAngle = (IfcPlaneAngleMeasure?)value;
					 break;
				case 4:
					 @CharacterSpacing = (IfcSizeSelect)value;
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(string propName, object value)
		{
			switch(propName)
			{
				case "BoxHeight":
					 @BoxHeight = (IfcPositiveLengthMeasure?)value;
					 break;
				case "BoxWidth":
					 @BoxWidth = (IfcPositiveLengthMeasure?)value;
					 break;
				case "BoxSlantAngle":
					 @BoxSlantAngle = (IfcPlaneAngleMeasure?)value;
					 break;
				case "BoxRotateAngle":
					 @BoxRotateAngle = (IfcPlaneAngleMeasure?)value;
					 break;
				case "CharacterSpacing":
					 @CharacterSpacing = (IfcSizeSelect)value;
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}
		#endregion


		#region IPersist implementation
		public virtual void Parse(int propIndex, IPropertyValue value)
		{
            throw new System.NotImplementedException();
		}
		
		public virtual string WhereRule() 
		{
            throw new System.NotImplementedException();
		}
		#endregion

		
	}
}