// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		16.09.2015 04:22:58
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc2x3.MeasureResource;
using System.Collections.Generic;
using System.ComponentModel;
using System;
using Xbim.Common;
using Xbim.Common.Exceptions;

namespace Xbim.Ifc2x3.CostResource
{
	[EntityName("IFCAPPLIEDVALUERELATIONSHIP", 691)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @IfcAppliedValueRelationship : INotifyPropertyChanged, IInstantiableEntity
	{
		#region Implementation of IPersistEntity
		public int EntityLabel {get; internal set;}
		
		public IModel Model { get; internal set; }
		
		public bool Activated { get; internal set; }

		public void Activate(bool write)
		{
			if (Activated) return; //activation can only happen once in a lifetime of the object

			Model.Activate(this, write);
			Activated = true;
		}

		public void Activate (Action activation)
		{
			activation();
			Activated = true;
		}
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcAppliedValueRelationship(IModel model) 		{ 
			Model = model; 
			_components = new ItemSet<IfcAppliedValue>( this );
		}

		#region Explicit attribute fields
		private IfcAppliedValue _componentOfTotal;
		private ItemSet<IfcAppliedValue> _components;
		private IfcArithmeticOperatorEnum _arithmeticOperator;
		private IfcLabel? _name;
		private IfcText? _description;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(0, EntityAttributeState.Mandatory)]
		public IfcAppliedValue @ComponentOfTotal 
		{ 
			get 
			{
				if(Activated) return _componentOfTotal;
				
				Model.Activate(this, true);
				Activated = true;
				return _componentOfTotal;
			} 
			set
			{
				SetValue( v =>  _componentOfTotal = v, _componentOfTotal, value,  "ComponentOfTotal");
			} 
		}
	
		[EntityAttribute(1, EntityAttributeState.Mandatory)]
		public ItemSet<IfcAppliedValue> @Components 
		{ 
			get 
			{
				if(Activated) return _components;
				
				Model.Activate(this, true);
				Activated = true;
				return _components;
			} 
			set
			{
				SetValue( v =>  _components = v, _components, value,  "Components");
			} 
		}
	
		[EntityAttribute(2, EntityAttributeState.Mandatory)]
		public IfcArithmeticOperatorEnum @ArithmeticOperator 
		{ 
			get 
			{
				if(Activated) return _arithmeticOperator;
				
				Model.Activate(this, true);
				Activated = true;
				return _arithmeticOperator;
			} 
			set
			{
				SetValue( v =>  _arithmeticOperator = v, _arithmeticOperator, value,  "ArithmeticOperator");
			} 
		}
	
		[EntityAttribute(3, EntityAttributeState.Optional)]
		public IfcLabel? @Name 
		{ 
			get 
			{
				if(Activated) return _name;
				
				Model.Activate(this, true);
				Activated = true;
				return _name;
			} 
			set
			{
				SetValue( v =>  _name = v, _name, value,  "Name");
			} 
		}
	
		[EntityAttribute(4, EntityAttributeState.Optional)]
		public IfcText? @Description 
		{ 
			get 
			{
				if(Activated) return _description;
				
				Model.Activate(this, true);
				Activated = true;
				return _description;
			} 
			set
			{
				SetValue( v =>  _description = v, _description, value,  "Description");
			} 
		}
	
		#endregion

		#region Inverse attributes

		#endregion

		#region INotifyPropertyChanged implementation
		 
		public event PropertyChangedEventHandler PropertyChanged;

		protected void NotifyPropertyChanged( string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

		#endregion

		#region Transactional property setting

		protected void SetValue<TProperty>(Action<TProperty> setter, TProperty oldValue, TProperty newValue, string notifyPropertyName)
		{

			if (!Model.IsTransactional)
			{
				setter(newValue);
				NotifyPropertyChanged(notifyPropertyName);
				return;
			}

			//check there is a transaction
			var txn = Model.CurrentTransaction;
			if (txn == null) throw new Exception("Operation out of transaction.");

			Action doAction = () => setter(newValue);
			Action undoAction = () => setter(oldValue);
			txn.AddReversibleAction(doAction, undoAction, this);
			setter(newValue);
			NotifyPropertyChanged(notifyPropertyName);
		}

		#endregion

		#region Index access
		private static readonly List<string> AttributeNames = new List<string>
		{
			"ComponentOfTotal",
			"Components",
			"ArithmeticOperator",
			"Name",
			"Description",
		};

		IEnumerable<string> IInstantiableEntity.PropertyNames { get { return AttributeNames; } }

		object IInstantiableEntity.GetValue(int index)
		{
			switch(index)
			{
				case 0: 
					return @ComponentOfTotal;
				case 1: 
					return @Components;
				case 2: 
					return @ArithmeticOperator;
				case 3: 
					return @Name;
				case 4: 
					return @Description;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		object IInstantiableEntity.GetValue(string name)
		{
			switch(name)
			{
				case "ComponentOfTotal":  
					return @ComponentOfTotal;
				case "Components":  
					return @Components;
				case "ArithmeticOperator":  
					return @ArithmeticOperator;
				case "Name":  
					return @Name;
				case "Description":  
					return @Description;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(int index, object value)
		{
			switch(index)
			{
				case 0:
					 @ComponentOfTotal = (IfcAppliedValue)value;
					 break;
				case 1:
					 @Components.Add((IfcAppliedValue)value);
					 break;
				case 2:
					 if (value != null) @ArithmeticOperator = (IfcArithmeticOperatorEnum)value;
					 break;
				case 3:
					 @Name = (IfcLabel?)value;
					 break;
				case 4:
					 @Description = (IfcText?)value;
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(string propName, object value)
		{
			switch(propName)
			{
				case "ComponentOfTotal":
					 @ComponentOfTotal = (IfcAppliedValue)value;
					 break;
				case "Components":
					 @Components.Add((IfcAppliedValue)value);
					 break;
				case "ArithmeticOperator":
					 if (value != null) @ArithmeticOperator = (IfcArithmeticOperatorEnum)value;
					 break;
				case "Name":
					 @Name = (IfcLabel?)value;
					 break;
				case "Description":
					 @Description = (IfcText?)value;
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}
		#endregion



		#region IPersist implementation
		public virtual void Parse(int propIndex, IPropertyValue value)
		{
			switch (propIndex)
			{
				case 0: 
					_componentOfTotal = (IfcAppliedValue)(value.EntityVal);
					return;
				case 1: 
					if (_components == null) _components = new ItemSet<IfcAppliedValue>( this );
					_components.Add((IfcAppliedValue)value.EntityVal);
					return;
				case 2: 
                    _arithmeticOperator = (IfcArithmeticOperatorEnum) System.Enum.Parse(typeof (IfcArithmeticOperatorEnum), value.EnumVal, true);
					return;
				case 3: 
					_name = value.StringVal;
					return;
				case 4: 
					_description = value.StringVal;
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		
		public virtual string WhereRule() 
		{
			return "";
		}
		#endregion

		
	}
}