// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		09/09/2015 04:20:44
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.UtilityResource;
using Xbim.Ifc4.MeasureResource;
using Xbim.Ifc4.GeometricConstraintResource;
using Xbim.Ifc4.RepresentationResource;
using System.Collections.Generic;
using Xbim.Common;

namespace Xbim.Ifc4.StructuralElementsDomain
{
	[EntityName("IFCTENDON", 695)]
	public  partial class @IfcTendon : IfcReinforcingElement, IInstantiableEntity
	{
		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcTendon(IModel model) : base(model) 		{ 
			Model = model; 
		}

		#region Explicit attribute fields
		private IfcTendonTypeEnum? _predefinedType;
		private IfcPositiveLengthMeasure? _nominalDiameter;
		private IfcAreaMeasure? _crossSectionArea;
		private IfcForceMeasure? _tensionForce;
		private IfcPressureMeasure? _preStress;
		private IfcNormalisedRatioMeasure? _frictionCoefficient;
		private IfcPositiveLengthMeasure? _anchorageSlip;
		private IfcPositiveLengthMeasure? _minCurvatureRadius;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(9, EntityAttributeState.Optional)]
		public IfcTendonTypeEnum? @PredefinedType 
		{ 
			get 
			{
				if(Activated) return _predefinedType;
				
				Model.Activate(this, true);
				Activated = true;
				return _predefinedType;
			} 
			set
			{
				SetValue( v =>  _predefinedType = v, _predefinedType, value,  "PredefinedType");
			} 
		}
	
		[EntityAttribute(10, EntityAttributeState.Optional)]
		public IfcPositiveLengthMeasure? @NominalDiameter 
		{ 
			get 
			{
				if(Activated) return _nominalDiameter;
				
				Model.Activate(this, true);
				Activated = true;
				return _nominalDiameter;
			} 
			set
			{
				SetValue( v =>  _nominalDiameter = v, _nominalDiameter, value,  "NominalDiameter");
			} 
		}
	
		[EntityAttribute(11, EntityAttributeState.Optional)]
		public IfcAreaMeasure? @CrossSectionArea 
		{ 
			get 
			{
				if(Activated) return _crossSectionArea;
				
				Model.Activate(this, true);
				Activated = true;
				return _crossSectionArea;
			} 
			set
			{
				SetValue( v =>  _crossSectionArea = v, _crossSectionArea, value,  "CrossSectionArea");
			} 
		}
	
		[EntityAttribute(12, EntityAttributeState.Optional)]
		public IfcForceMeasure? @TensionForce 
		{ 
			get 
			{
				if(Activated) return _tensionForce;
				
				Model.Activate(this, true);
				Activated = true;
				return _tensionForce;
			} 
			set
			{
				SetValue( v =>  _tensionForce = v, _tensionForce, value,  "TensionForce");
			} 
		}
	
		[EntityAttribute(13, EntityAttributeState.Optional)]
		public IfcPressureMeasure? @PreStress 
		{ 
			get 
			{
				if(Activated) return _preStress;
				
				Model.Activate(this, true);
				Activated = true;
				return _preStress;
			} 
			set
			{
				SetValue( v =>  _preStress = v, _preStress, value,  "PreStress");
			} 
		}
	
		[EntityAttribute(14, EntityAttributeState.Optional)]
		public IfcNormalisedRatioMeasure? @FrictionCoefficient 
		{ 
			get 
			{
				if(Activated) return _frictionCoefficient;
				
				Model.Activate(this, true);
				Activated = true;
				return _frictionCoefficient;
			} 
			set
			{
				SetValue( v =>  _frictionCoefficient = v, _frictionCoefficient, value,  "FrictionCoefficient");
			} 
		}
	
		[EntityAttribute(15, EntityAttributeState.Optional)]
		public IfcPositiveLengthMeasure? @AnchorageSlip 
		{ 
			get 
			{
				if(Activated) return _anchorageSlip;
				
				Model.Activate(this, true);
				Activated = true;
				return _anchorageSlip;
			} 
			set
			{
				SetValue( v =>  _anchorageSlip = v, _anchorageSlip, value,  "AnchorageSlip");
			} 
		}
	
		[EntityAttribute(16, EntityAttributeState.Optional)]
		public IfcPositiveLengthMeasure? @MinCurvatureRadius 
		{ 
			get 
			{
				if(Activated) return _minCurvatureRadius;
				
				Model.Activate(this, true);
				Activated = true;
				return _minCurvatureRadius;
			} 
			set
			{
				SetValue( v =>  _minCurvatureRadius = v, _minCurvatureRadius, value,  "MinCurvatureRadius");
			} 
		}
	
		#endregion

		#region Inverse attributes

		#endregion

		#region Index access
		private readonly List<string> _attributeNames = new List<string>
		{
			"GlobalId",
			"OwnerHistory",
			"Name",
			"Description",
			"ObjectType",
			"ObjectPlacement",
			"Representation",
			"Tag",
			"SteelGrade",
			"PredefinedType",
			"NominalDiameter",
			"CrossSectionArea",
			"TensionForce",
			"PreStress",
			"FrictionCoefficient",
			"AnchorageSlip",
			"MinCurvatureRadius",
		};

		IEnumerable<string> IInstantiableEntity.PropertyNames { get { return _attributeNames; } }

		object IInstantiableEntity.GetValue(int index)
		{
			switch(index)
			{
				case 0: 
					return @GlobalId;
				case 1: 
					return @OwnerHistory;
				case 2: 
					return @Name;
				case 3: 
					return @Description;
				case 4: 
					return @ObjectType;
				case 5: 
					return @ObjectPlacement;
				case 6: 
					return @Representation;
				case 7: 
					return @Tag;
				case 8: 
					return @SteelGrade;
				case 9: 
					return @PredefinedType;
				case 10: 
					return @NominalDiameter;
				case 11: 
					return @CrossSectionArea;
				case 12: 
					return @TensionForce;
				case 13: 
					return @PreStress;
				case 14: 
					return @FrictionCoefficient;
				case 15: 
					return @AnchorageSlip;
				case 16: 
					return @MinCurvatureRadius;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		object IInstantiableEntity.GetValue(string name)
		{
			switch(name)
			{
				case "GlobalId":  
					return @GlobalId;
				case "OwnerHistory":  
					return @OwnerHistory;
				case "Name":  
					return @Name;
				case "Description":  
					return @Description;
				case "ObjectType":  
					return @ObjectType;
				case "ObjectPlacement":  
					return @ObjectPlacement;
				case "Representation":  
					return @Representation;
				case "Tag":  
					return @Tag;
				case "SteelGrade":  
					return @SteelGrade;
				case "PredefinedType":  
					return @PredefinedType;
				case "NominalDiameter":  
					return @NominalDiameter;
				case "CrossSectionArea":  
					return @CrossSectionArea;
				case "TensionForce":  
					return @TensionForce;
				case "PreStress":  
					return @PreStress;
				case "FrictionCoefficient":  
					return @FrictionCoefficient;
				case "AnchorageSlip":  
					return @AnchorageSlip;
				case "MinCurvatureRadius":  
					return @MinCurvatureRadius;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(int index, object value)
		{
			switch(index)
			{
				case 0:
					 if (value != null) @GlobalId = (IfcGloballyUniqueId)value;
					 break;
				case 1:
					 @OwnerHistory = (IfcOwnerHistory)value;
					 break;
				case 2:
					 @Name = (IfcLabel?)value;
					 break;
				case 3:
					 @Description = (IfcText?)value;
					 break;
				case 4:
					 @ObjectType = (IfcLabel?)value;
					 break;
				case 5:
					 @ObjectPlacement = (IfcObjectPlacement)value;
					 break;
				case 6:
					 @Representation = (IfcProductRepresentation)value;
					 break;
				case 7:
					 @Tag = (IfcIdentifier?)value;
					 break;
				case 8:
					 @SteelGrade = (IfcLabel?)value;
					 break;
				case 9:
					 @PredefinedType = (IfcTendonTypeEnum?)value;
					 break;
				case 10:
					 @NominalDiameter = (IfcPositiveLengthMeasure?)value;
					 break;
				case 11:
					 @CrossSectionArea = (IfcAreaMeasure?)value;
					 break;
				case 12:
					 @TensionForce = (IfcForceMeasure?)value;
					 break;
				case 13:
					 @PreStress = (IfcPressureMeasure?)value;
					 break;
				case 14:
					 @FrictionCoefficient = (IfcNormalisedRatioMeasure?)value;
					 break;
				case 15:
					 @AnchorageSlip = (IfcPositiveLengthMeasure?)value;
					 break;
				case 16:
					 @MinCurvatureRadius = (IfcPositiveLengthMeasure?)value;
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(string propName, object value)
		{
			switch(propName)
			{
				case "GlobalId":
					 if (value != null) @GlobalId = (IfcGloballyUniqueId)value;
					 break;
				case "OwnerHistory":
					 @OwnerHistory = (IfcOwnerHistory)value;
					 break;
				case "Name":
					 @Name = (IfcLabel?)value;
					 break;
				case "Description":
					 @Description = (IfcText?)value;
					 break;
				case "ObjectType":
					 @ObjectType = (IfcLabel?)value;
					 break;
				case "ObjectPlacement":
					 @ObjectPlacement = (IfcObjectPlacement)value;
					 break;
				case "Representation":
					 @Representation = (IfcProductRepresentation)value;
					 break;
				case "Tag":
					 @Tag = (IfcIdentifier?)value;
					 break;
				case "SteelGrade":
					 @SteelGrade = (IfcLabel?)value;
					 break;
				case "PredefinedType":
					 @PredefinedType = (IfcTendonTypeEnum?)value;
					 break;
				case "NominalDiameter":
					 @NominalDiameter = (IfcPositiveLengthMeasure?)value;
					 break;
				case "CrossSectionArea":
					 @CrossSectionArea = (IfcAreaMeasure?)value;
					 break;
				case "TensionForce":
					 @TensionForce = (IfcForceMeasure?)value;
					 break;
				case "PreStress":
					 @PreStress = (IfcPressureMeasure?)value;
					 break;
				case "FrictionCoefficient":
					 @FrictionCoefficient = (IfcNormalisedRatioMeasure?)value;
					 break;
				case "AnchorageSlip":
					 @AnchorageSlip = (IfcPositiveLengthMeasure?)value;
					 break;
				case "MinCurvatureRadius":
					 @MinCurvatureRadius = (IfcPositiveLengthMeasure?)value;
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}
		#endregion

		#region Where rules
		/*CorrectPredefinedType:                              ((PredefinedType = IfcTendonTypeEnum.USERDEFINED) AND EXISTS (SELF\IfcObject.ObjectType));*/
		/*CorrectTypeAssigned:                              ('IFC4.IFCTENDONTYPE' IN TYPEOF(SELF\IfcObject.IsTypedBy[1].RelatingType));*/
		#endregion

		#region IPersist implementation
		void IPersist.Set(int propIndex, IPropertyValue value)
		{
            throw new System.NotImplementedException();
		}
		#endregion

		public  override string WhereRule() 
		{
			return "";
		}
	}
}