// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		08/09/2015 02:29:24
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.Ifc4.BuildingControlsDomain
{
	public enum IfcAlarmTypeEnum
	{
		@BELL ,
		@BREAKGLASSBUTTON ,
		@LIGHT ,
		@MANUALPULLBOX ,
		@SIREN ,
		@WHISTLE ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}