// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		08/09/2015 09:16:38
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc2x3.TopologyResource;
using Xbim.Common;

namespace Xbim.Ifc2x3.GeometricModelResource
{
	[EntityName("IFCMANIFOLDSOLIDBREP")]
	public abstract partial class @IfcManifoldSolidBrep : IfcSolidModel
	{
		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcManifoldSolidBrep(IModel model) : base(model) 		{ 
			Model = model; 
		}

		#region Explicit attribute fields
		private IfcClosedShell _outer;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(0, EntityAttributeState.Mandatory)]
		public IfcClosedShell @Outer 
		{ 
			get 
			{
				if(IsActivated) return _outer;
				
				Model.Activate(this, true);
				IsActivated = true;
				return _outer;
			} 
			set
			{
				SetValue( v =>  _outer = v, _outer, value,  "Outer");
			} 
		}
	
		#endregion

		#region Inverse attributes

		#endregion


		#region IPersist implementation
		#endregion

	}
}