// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//		16.09.2015 04:23:00
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using Xbim.Common;
using Xbim.Common.Exceptions;

namespace Xbim.Ifc2x3.GeometryResource
{
	[EntityName("IFCRATIONALBEZIERCURVE", 546)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @IfcRationalBezierCurve : IfcBezierCurve, IInstantiableEntity
	{
		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcRationalBezierCurve(IModel model) : base(model) 		{ 
			Model = model; 
			_weightsData = new ItemSet<double>( this );
		}

		#region Explicit attribute fields
		private ItemSet<double> _weightsData;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(5, EntityAttributeState.Mandatory)]
		public ItemSet<double> @WeightsData 
		{ 
			get 
			{
				if(Activated) return _weightsData;
				
				Model.Activate(this, true);
				Activated = true;
				return _weightsData;
			} 
			set
			{
				SetValue( v =>  _weightsData = v, _weightsData, value,  "WeightsData");
			} 
		}
	
		#endregion

		#region Inverse attributes

		#endregion

		#region Index access
		private static readonly List<string> AttributeNames = new List<string>
		{
			"Degree",
			"ControlPointsList",
			"CurveForm",
			"ClosedCurve",
			"SelfIntersect",
			"WeightsData",
		};

		IEnumerable<string> IInstantiableEntity.PropertyNames { get { return AttributeNames; } }

		object IInstantiableEntity.GetValue(int index)
		{
			switch(index)
			{
				case 0: 
					return @Degree;
				case 1: 
					return @ControlPointsList;
				case 2: 
					return @CurveForm;
				case 3: 
					return @ClosedCurve;
				case 4: 
					return @SelfIntersect;
				case 5: 
					return @WeightsData;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		object IInstantiableEntity.GetValue(string name)
		{
			switch(name)
			{
				case "Degree":  
					return @Degree;
				case "ControlPointsList":  
					return @ControlPointsList;
				case "CurveForm":  
					return @CurveForm;
				case "ClosedCurve":  
					return @ClosedCurve;
				case "SelfIntersect":  
					return @SelfIntersect;
				case "WeightsData":  
					return @WeightsData;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(int index, object value)
		{
			switch(index)
			{
				case 0:
					 if (value != null) @Degree = (long)value;
					 break;
				case 1:
					 @ControlPointsList.Add((IfcCartesianPoint)value);
					 break;
				case 2:
					 if (value != null) @CurveForm = (IfcBSplineCurveForm)value;
					 break;
				case 3:
					 @ClosedCurve = (bool?)value;
					 break;
				case 4:
					 @SelfIntersect = (bool?)value;
					 break;
				case 5:
					 @WeightsData.Add((double)value);
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}

		void IInstantiableEntity.SetValue(string propName, object value)
		{
			switch(propName)
			{
				case "Degree":
					 if (value != null) @Degree = (long)value;
					 break;
				case "ControlPointsList":
					 @ControlPointsList.Add((IfcCartesianPoint)value);
					 break;
				case "CurveForm":
					 if (value != null) @CurveForm = (IfcBSplineCurveForm)value;
					 break;
				case "ClosedCurve":
					 @ClosedCurve = (bool?)value;
					 break;
				case "SelfIntersect":
					 @SelfIntersect = (bool?)value;
					 break;
				case "WeightsData":
					 @WeightsData.Add((double)value);
					 break;
				default:
					throw new System.IndexOutOfRangeException();
			}
		}
		#endregion



		#region IPersist implementation
		public  override void Parse(int propIndex, IPropertyValue value)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
				case 2: 
				case 3: 
				case 4: 
					base.Parse(propIndex, value); 
					return;
				case 5: 
					if (_weightsData == null) _weightsData = new ItemSet<double>( this );
					_weightsData.Add(value.RealVal);
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		
		public  override string WhereRule() 
		{
            throw new System.NotImplementedException();
		/*WR1:	WR1 : SIZEOF(WeightsData) = SIZEOF(SELF\IfcBSplineCurve.ControlPointsList);*/
		/*WR2:	WR2 : IfcCurveWeightsPositive(SELF);*/
		}
		#endregion

		
	}
}