// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.ProductExtension;
using Xbim.Common;
using Xbim.Common.Exceptions;

namespace Xbim.Ifc4.SharedBldgServiceElements
{
	[ExpressType("IFCDISTRIBUTIONFLOWELEMENTTYPE", 575)]
	// ReSharper disable once PartialTypeWithSinglePart
	public abstract partial class @IfcDistributionFlowElementType : IfcDistributionElementType, System.Collections.Generic.IEqualityComparer<@IfcDistributionFlowElementType>, System.IEquatable<@IfcDistributionFlowElementType>
	{
		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcDistributionFlowElementType(IModel model) : base(model) 		{ 
			Model = model; 
		}




		#region IPersist implementation
		public  override void Parse(int propIndex, IPropertyValue value)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
				case 2: 
				case 3: 
				case 4: 
				case 5: 
				case 6: 
				case 7: 
				case 8: 
					base.Parse(propIndex, value); 
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		
		public  override string WhereRule() 
		{
			return "";
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@IfcDistributionFlowElementType other)
	    {
	        return this == other;
	    }


        public static bool operator ==(@IfcDistributionFlowElementType left, @IfcDistributionFlowElementType right)
        {
            // If both are null, or both are same instance, return true.
            if (ReferenceEquals(left, right))
                return true;

            // If one is null, but not both, return false.
            if (ReferenceEquals(left, null) || ReferenceEquals(right, null))
                return false;

            return (left.EntityLabel == right.EntityLabel) && (left.Model == right.Model);

        }

        public static bool operator !=(@IfcDistributionFlowElementType left, @IfcDistributionFlowElementType right)
        {
            return !(left == right);
        }


        public bool Equals(@IfcDistributionFlowElementType x, @IfcDistributionFlowElementType y)
        {
            return x == y;
        }

        public int GetHashCode(@IfcDistributionFlowElementType obj)
        {
            return obj == null ? -1 : obj.GetHashCode();
        }
        #endregion
	}
}